[versions]
kotlin = "2.3.10"
composeMultiplatform = "1.10.1"
oskitKmp = "5.1.0-beta5"
oskitCompose = "4.1.0-beta6"
androidGradlePlugin = "9.0.1"
android-compileSdk = "36"
android-minSdk = "28"
androidx-activityCompose = "1.12.4"
androidx-appcompat = "1.7.1"
androidx-core-ktx = "1.17.0"
junit = "4.13.2"
koinCore = "4.1.1"
kotlinxAtomicfu = "0.31.0"
kotlinxCoroutinesCore = "1.10.2"
kotlinxDatetime = "0.7.1"
skie = "0.10.10"
material-icons = "1.7.3"

[libraries]
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinxAtomicfu" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinCore" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
oskit-compose = { module = "com.outsidesource:oskit-compose", version.ref = "oskitCompose" }
oskit-kmp = { module = "com.outsidesource:oskit-kmp", version.ref = "oskitKmp" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
compose-ui-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
compose-material = { module = "org.jetbrains.compose.material:material", version.ref = "composeMultiplatform" }
material-icons = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "material-icons" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
skie = { id = "co.touchlab.skie", version.ref = "skie" }