[versions]
kotlin = "2.2.0"
agp = "8.10.1"
android-compileSdk = "36"
android-minSdk = "28"
android-targetSdk = "36"
androidx-activityCompose = "1.10.1"
androidx-appcompat = "1.7.1"
androidx-core-ktx = "1.16.0"
compose = "1.8.2"
junit = "4.13.2"
kermit = "2.0.5"
koinCore = "4.0.0"
kotlinxAtomicfu = "0.26.1"
kotlinxCoroutinesCore = "1.10.2"
kotlinxDatetime = "0.6.2"
okio = "3.9.1"
oskitCompose = "4.1.0"
oskitKmp = "5.1.0"
skie = "0.10.4"
compose-multiplatform = "1.8.3"
material-icons = "1.7.3"

[libraries]
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinxAtomicfu" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinCore" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
oskit-compose = { module = "com.outsidesource:oskit-compose", version.ref = "oskitCompose" }
oskit-kmp = { module = "com.outsidesource:oskit-kmp", version.ref = "oskitKmp" }
compose-multiplatform = { module = "androidx.compose.ui:ui", version.ref = "compose-multiplatform" }
material-icons = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "material-icons" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
skie = { id = "co.touchlab.skie", version.ref = "skie" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }